### PR TITLE
tag: add part and reason params for {{update}}

### PR DESCRIPTION
**Pull request by loganrosen**
Adding support for the suggested `part` and `reason` parameters of `{{update}}`. Tested on [the test wiki](https://test.wikipedia.org/w/index.php?title=Watty62_test&action=history).

### CODE REVIEW

**Comment by NovemLinguae** [comment]
Hey there. I removed the "type" parameter since the options are article (default) and section, and Twinkle can only place tags at the top of the article at the moment, so would basically never need to use section. You OK with this change? If so I think this is ready to merge. Thanks.

**Comment by NovemLinguae** [comment]
Note to self: Look into widening the reason box.

**Comment by loganrosen** [comment]
The `part` parameter can be more descriptive than just "section" (see the first example in [the usage section](https://en.wikipedia.org/wiki/Template:Update#Usage)). I'm okay removing it regardless if you think it won't add much value.

**Comment by NovemLinguae** [comment]
Ah, I see, thank you for the explanation. I added back `updatePart`. How's it look now?

**Comment by loganrosen** [comment]
Looks good to me, thanks!

**Pull request merged**
