### PR TITLE
tag: Add R to subpage

### PR DESCRIPTION
**Pull request by TheTVExpert**
Per https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Redirect_tagging_doesn't_include_{{R_to_subpage}}

### CODE REVIEW

**Comment by Amorymeltzer** [comment]
Left a comment at WT:TW, but right now, this we the list form Template:R template index, which is not all-inclusive.

**Comment by TheTVExpert** [comment]
@Amorymeltzer I realized this while I wrote it, but I thought I'd add it anyway due to the 2900 transclusions.

**Comment by Amorymeltzer** [comment]
I'm not inherently opposed, I just think it's good to have some guiding plan.  I don't profess to know *why* the template is limited, but possibly better as an on-wiki conversation.

**Comment by TheTVExpert** [comment]
That is fine by me.

**Review by DannyS712 — APPROVED** [review]

**Review by siddharthvp — APPROVED** [review]

**Comment by siddharthvp** [comment]
I think the issue of this not being in Template:R template index can be fixed by just adding it there?

**Pull request merged**
