### PR TITLE
morebits: Correct jquery dialog event name

### PR DESCRIPTION
**Pull request by Xi-Plus**
See https://api.jqueryui.com/dialog/#event-resizeStop

### CODE REVIEW

**Review by Amorymeltzer — APPROVED** [review]
Weird!  Curious how you found it, @Xi-Plus.  AFAICT, it doesn't actually make a difference given how we use it, is that right?

**Comment by Xi-Plus** [comment]
Yes. The typo didn't cause any bug.

**Comment by siddharthvp** [comment]
The linked docs are for a different version, but this nevertheless applies to our jQuery.ui version: https://github.com/wikimedia/mediawiki/blob/b1c3685a1a4c15e3431ceb2fec59c94f4984e4ad/resources/lib/jquery.ui/jquery.ui.dialog.js#L472

**Comment by Amorymeltzer** [comment]
https://api.jqueryui.com/1.9/dialog/#event-resizeStop

**Pull request merged**
