### PR TITLE
arv: censor username if offensive username is ticked

### PR DESCRIPTION
**Pull request by darmanilink**
See: https://test.wikipedia.org/wiki/Wikipedia:Usernames_for_administrator_attention for testing

### CODE REVIEW

**Comment by darmanilink** [comment]
ah, my bad, ublock was messing with me seeing the linter errors and i had to guess
ill fix those now

**Comment by NovemLinguae** [comment]
No worries. We always squash :)

**Comment by darmanilink** [comment]
I am so sorry about this

**Comment by darmanilink** [comment]
made sure in my sleep deprivation i didn't mess something up while trying to fix the linting. Looks to be good now. 
My apologies, nothing more incoming unless you want a change

**Pull request merged**
