### PR TITLE
#1542 protect: rename {{pp-30-500}} to {{pp-extended}}

### PR DESCRIPTION
**Pull request by codesmith25103**
Sir, I have rename 'pp-30-500' to 'pp-extended'.

### CODE REVIEW

**Review by azatoth — CHANGES_REQUESTED** [review]
There's sadly a lot of unrelated changes like formatting that makes it difficult to to pinpoint what has actually been changed. If a formatting change is warranted in a PR I suggest place them in a separate commit so it can be separated.

Also I don't think the changes in `package-lock.json` is warranted.

**Comment by NovemLinguae** [comment]
The package-lock.json changes are good, but should be a separate PR. I'll file a PR for that.

Did you run a code beautifier/code style fixer on these files? There are a bunch of changes unrelated to the original issue. Can you perhaps undo those changes and resubmit, to make this easier to evaluate?

**Comment by codesmith25103** [comment]
Yes Sir, code formatter had given some extra spaces in code. I will try to undo it and then I will resubmit the code.

**Comment by codesmith25103** [comment]
Sir, Please merge it

**Comment by NovemLinguae** [comment]
Sorry this patch took so long to review.

After thinking about this, I think it'd be OK to continue using "30-500" in internal names. So I have undone that part of your patch. That should make your patch simpler/less risky/easier to review.

Looks good now. Merging. Thank you for contributing this patch.

If you do more patches for us in the future, you may want to use a git "branch". Using a master branch on a forked repo can cause problems if you submit multiple patches at the same time. So one custom branch per patch is usually a good idea.

**Pull request merged**
