### PR TITLE
twinkleblock: "Vandalism-only account": Link to policy rather than essay

### PR DESCRIPTION
**Pull request by ToBeFree**
"WP:Vandalism-only account" is an essay, "WP:DISRUPTONLY" is a policy section.

### CODE REVIEW

**Comment by Amorymeltzer** [comment]
FWIW, see [[MediaWiki:Ipbreason-dropdown]]

**Comment by ToBeFree** [comment]
Ah, it's in there too. Well, I rarely use the manual block form, and I never use it with this dropdown reason. I thus don't feel a need for me to change the system-wide MediaWiki builtin dropdown in this way. If Twinkle, on the other hand, had statistics about which block reason is used how often by whom, I'd probably appear in the top X for this one.

**Comment by NovemLinguae** [comment]
I'll merge this if my code review suggestion above is addressed. Feel free to upload a new patchset.

**Comment by ToBeFree** [comment]
I hope this addresses what you had noted; the note was lost in an attempt to clean up my followers list, which is only possible by blocking (and then unblocking) users on GitHub. This probably removed the review as well, though; sorry for that.

**Pull request merged**
