### PR TITLE
warn: Add uw-translation

### LINKED ISSUE #1729: add {{Uw-translation}}
Requested by Asilvering at https://en.wikipedia.org/wiki/Special:Permalink/1140762591#Translation_template

### PR DESCRIPTION
**Pull request by earlt612**
Will resolve #1729

### CODE REVIEW

**Comment by earlt612** [comment]
Closed so I can work on the code

**Comment by NovemLinguae** [comment]
Linter says every line has an extra tab. Was that intentional? May want to reset the file to its original state, then make your changes. To see if you did it right, you can click the "Files changed" tab and see if it look reasonable.

image

**Comment by earlt612** [comment]
Looking

**Comment by earlt612** [comment]
Good to go now

**Comment by NovemLinguae** [comment]
I tried to just make the 2 requested changes myself, but I think because you didn't use a custom branch (you used the master branch), I am unable to push changes.

Anyway, if you can make the changes yourself, this will be ready to accept. Thank you.

**Comment by earlt612** [comment]
@NovemLinguae Can you explain what changes you want me to make?

**Comment by NovemLinguae** [comment]
Sure. You can scroll up a bit to see my proposed changes.

image

image

**Review by NovemLinguae — CHANGES_REQUESTED** [review]

**Comment by earlt612** [comment]
Requested changes have been made

**Pull request merged**
