### PR TITLE
twinkle: add preferences link to dropdown menu

### LINKED ISSUE #1326: Add preferences to dropdown menu?
Just a suggestion. Consider adding "Prefs" (preferences) to the Twinkle dropdown menu, at the bottom. That seems like an intuitive spot for it. It would point to the page Wikipedia:Twinkle/Preferences, so you wouldn't have to type WP:TWINKLE and click the link at the top, which is more steps than ideal.

### PR DESCRIPTION
**Pull request by NovemLinguae**
Fixes #1326

I think myself and Qwerfjkl are in favor (see onwiki discussion at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Add_%22Prefs%22_to_Twinkle_menu%3F), and @Amorymeltzer had some reservations. Open to feedback.

### CODE REVIEW

**Comment by Amorymeltzer** [comment]
I'll reiterate what I said earlier, in particular that adding another tab for non-vector/non-timeless users is a big deal, especially as the name "prefs" is vague and prone to confusion/misleading.

**Comment by NovemLinguae** [comment]
How about renaming Prefs to Config?

So of the 5 official and maintained skins, Non-Vector, non-Timeless just leaves us with MonoBook that's affected, right? For me, it overflows no matter what, so dunno if that's a blocker. The long term fix for that is probably ticket #716.

Guess this will die on the vine unless someone else weighs in. Sounds like you're not in favor. Ah well.

**Comment by NovemLinguae** [comment]
Hey I just had a good idea. How about we only have "Config" display for Vector and Timeless. Any objections to that?

**Comment by NovemLinguae** [comment]
Hi @Amorymeltzer. Sorry to bug you again. Was just wondering if my two changes above assuage your concern? Thanks for your time.

**Comment by Amorymeltzer** [comment]
Certainly better that way

**Pull request merged**
