### PR TITLE
prod: add nomreason to old prod

### PR DESCRIPTION
**Pull request by TheTVExpert**
Per https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&diff=988006985&oldid=987953219

### CODE REVIEW

**Comment by Amorymeltzer** [comment]
Noting @siddharthvp's valid points on-wiki, this would leave BLPPRODs blank, yeah?  An empty `reason` is fine for the log since it's already noted, but for this it'd be no good and something should be filled in.

**Comment by TheTVExpert** [comment]
Once there is consensus on-wiki, I'll alter this PR to reflect the result.

**Comment by TheTVExpert** [comment]
@siddharthvp, since there was no opposition to your proposal, could you add your new parameters to the template

**Comment by siddharthvp** [comment]
@TheTVExpert Sorry missed your message. I'll eventually look into editing the template, but would be grateful if someone else does it!

Marking this PR as a draft as it can't be merged as of now.

**Pull request closed without merging**
